### ISSUE TITLE
provide a method to view the CharTrie graphically (feature request)

### ISSUE THREAD

**Issue by manthanchauhan** [google/pygtrie#25]
It would be great if a graphical view can be implemented for CharTries. ie,
trie['hi'] = 5
trie['he'] = 6

HTML can be used to produce,
* h      i -> 5
           e -> 6

This feature can be useful for debugging or applications where close interactions with the data structure is required.

**Comment by mina86** [comment]
This is a rather specific request and I don’t think it belongs to a generic library such as pygtrie. For example, why HTML? Why not LaTeX? Or roff? There should be enough methods in the class to allow implementation of such graphical view to whatever format one desires. If there’s some generic traversal method which is lacking and which would make such implementation easier, we could discuss adding that.

**Comment by manthanchauhan** [comment]
I think graphical data interaction could become a highly advantageous and in-demand feature. The use of HTML is because of it's popularity, simplicity and, because the application being for developer use, not for UI.

**Comment by manthanchauhan** [comment]
As per your recommendation I'll reiterate over the codebase to see if it lacks any such traversal method.

**Comment by mina86** [comment]
If this is for developers than I’d much rather see it as some separate contrib code rather than part of the interface of the class. Once it’s added as a method it becomes an API which needs to be maintained.

**Comment by manthanchauhan** [comment]
I think, traverse is strong enough to provide ease in implementing any such graphical functionality, though it seems a little complicated to use. I'm closing this issue for now.
