### ISSUE TITLE
BUG no correct trie

### ISSUE THREAD

**Issue by desplenterkarel** [google/pygtrie#39]
when i use the CHARTRIE en give it a dicitonary to make a trie of it false to do so corectly.
For example giving the trei the words "NPM" en "NPS", among others. 
gives folowing path :
![image](https://user-images.githubusercontent.com/57403267/155323062-882839b1-6bba-4ec6-9fad-78c811b26e03.png)
while the word "NVG" does get corectly indexed:
![image](https://user-images.githubusercontent.com/57403267/155323341-e901e034-f02e-4598-82e4-cc53ede5b8d4.png)
What is wrong?

**Comment by mina86** [comment]
Could you provide a minimal example of failing code?  I don’t quite
know what you mean.  If you initialise a trie with keys ‘NPM’ and
‘NPS’ than root, ‘N’ and ‘NP’ nodes are observable when traversing the
path and this works correctly:

```python
import pygtrie

t = pygtrie.CharTrie({'NPM': None, 'NPS': None})
for k in t:
        print(k)
# → NPM
# → NPS
for step in t.walk_towards('NPM'):
        print(f'<{step.key}>')
# → <>
# → <N>
# → <NP>
# → <NPM>
```

**Comment by desplenterkarel** [comment]
ah i see i was confused by the keys and the nodes. I was under the impresion that it gave back the prefix of the nodes but it are only the keys that you provide your self, right? 

I loaded in a hole text where NP is not a word but NPM and NPS are.
So when printing the folowing i expeted 'NP' to be in the list but now i know that was wrong.
print( list(test.prefixes("NPM")))
print( list(test.prefixes("NPS")))
print( list(test.prefixes("NVG")))

Thank you for the quick help, i was at fault.
