### ISSUE TITLE
Inconsistent names?

### ISSUE THREAD

**Issue by pombredanne** [google/pygtrie#4]
Just a minor stuff but the repo is named pytrie, the Pypi package pygtrie and the python module trie....
Could it be worth to have a single name, such as pygtrie?
Thank you for your kind consideration!

**Comment by mina86** [comment]
On Mon, Dec 14 2015, Philippe Ombredanne wrote:
> Just a minor stuff but the repo is named pytrie, the Pypi package
> pygtrie and the python module trie....  Could it be worth to have
> a single name, such as pygtrie?

The reason for PyPI package not being pytrie is that the name has
already been taken.

I’m open to suggestions for standardising names.

Putting code into __init__.py or doing ‘__all__ = ('trie',)’ magic there
could solve part of the issue.

**Comment by mina86** [comment]
OK, I’ve renamed the repository to pygtrie and the old name seems to work well as a redirect so hopefully nothing broke. I’m still wondering what to do with the imports. I’ve pushed experimental branch which does the renames, would welcome comments.

**Comment by pombredanne** [comment]
@mina86 you wrote:
> I’m open to suggestions for standardising names.
> [...]
> I’ve pushed experimental branch which does the renames, would welcome comments.

pygtrie LGTM :)
And better, there is already a comic strip http://www.calamitiesofnature.com/archive/294.jpg , a tee-shirt and a logo for it: http://www.spiffystudios.com/pigtree-shirt/
